---
  - name: Apply templates
    template:  src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode}}
    with_items:
      - { src: 'templates/dev-challenge.env.j2', dest: '/home/vagrant/dev-challenge.env', owner: 'vagrant', group: 'vagrant', mode: '0655'}
      - { src: 'templates/docker-compose.yml.j2', dest: '/home/vagrant/docker-compose.yml', owner: 'vagrant', group: 'vagrant', mode: '0655'}
      - { src: 'templates/rsyslog.conf.j2', dest: '/etc/rsyslog.conf ', owner: 'root', group: 'root', mode: '0622'}
    become: true
      
  - name: "Docker Composes"
    command: docker-compose up -d
    become: true